name: Node.js Package

on: push

jobs:
  ecr_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: docker-practice/actions-setup-docker
      - run: docker build ${{ secrets.ECR_ENDPOINT_SAMPLE_1 }} packages/server/sample1
      - run: docker build ${{ secrets.ECR_ENDPOINT_SAMPLE_2 }} packages/server/sample2
      - name: Push to ECR sample1
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          image: ${{ secrets.ECR_ENDPOINT_SAMPLE_1 }}:latest
      - name: Push to ECR sample2
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          image: ${{ secrets.ECR_ENDPOINT_SAMPLE_1 }}:latest
