name: Node.js Package

on: push

jobs:
  ecr_push:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        images: [ 
          {name: "ECR_ENDPOINT_SAMPLE_1", path: "packages/server/sample1"}, 
          {name: "ECR_ENDPOINT_SAMPLE_2", path: "packages/server/sample2"}, 
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: docker-practice/actions-setup-docker@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: docker build -t ${{ secrets[matrix.images.name] }} ${{ matrix.images.path }}
      
      - run: docker push ${{ secrets[matrix.images.name] }}:latest
    
